/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package net.celestialdata.api;

import net.celestialdata.model.ArrayOfStatus;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-24T00:01:04.004Z[GMT]")
@Api(value = "status", description = "the status API")
public interface StatusApi {

    @ApiOperation(value = "Get the status of all the park features", nickname = "getStatus", notes = "Get the status of all the various waterpark features and return it as a JSON array.", response = ArrayOfStatus.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Feature status", response = ArrayOfStatus.class),
        @ApiResponse(code = 400, message = "Unable to get park statuses") })
    @RequestMapping(value = "/status",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ArrayOfStatus> getStatus();

}
