/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package net.celestialdata.api;

import net.celestialdata.model.FeatureStatus;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.*;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-24T00:01:04.004Z[GMT]")
@Api(value = "toggle", description = "the toggle API")
public interface ToggleApi {

    @ApiOperation(value = "Toggle a water feature on or off", nickname = "toggleFeature", notes = "Toggle a water feature on or off. It will be switched to whatever state it is not currently in.", response = FeatureStatus.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Feature toggled successfully", response = FeatureStatus.class),
        @ApiResponse(code = 400, message = "Unknown Water Feature") })
    @RequestMapping(value = "/toggle",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<FeatureStatus> toggleFeature(@NotNull @ApiParam(value = "The name of the water feature to toggle.", required = true) @Valid @RequestParam(value = "name", required = true) String name);

}
